2023-10-26 11:05:59,137:DEBUG:certbot._internal.main:certbot version: 2.7.3
2023-10-26 11:05:59,137:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-10-26 11:05:59,137:DEBUG:certbot._internal.main:Arguments: ['-v', '--webroot-path=/var/www/public', '--email', 'alexrubl@mail.ru', '--agree-tos', '--no-eff-email', '--staging', '--http-01-port', '8082', '-d', 'cinemapay.shtorm-cinema.ru:26443']
2023-10-26 11:05:59,137:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-10-26 11:05:59,143:DEBUG:certbot._internal.log:Root logging level set at 20
2023-10-26 11:05:59,143:DEBUG:certbot._internal.plugins.selection:Requested authenticator None and installer None
2023-10-26 11:05:59,144:DEBUG:certbot._internal.plugins.selection:Multiple candidate plugins: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7f1f501056f0>
Prep: True

* webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f1f501042e0>
Prep: True
2023-10-26 11:05:59,144:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1581, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/selection.py", line 250, in choose_configurator_plugins
    authenticator = pick_authenticator(config, req_auth, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/selection.py", line 46, in pick_authenticator
    return pick_plugin(
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/selection.py", line 124, in pick_plugin
    plugin_ep1 = choose_plugin(list(prepared.values()), question)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/selection.py", line 155, in choose_plugin
    code, index = display_util.menu(question, opts, force_interactive=True)
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 80, in menu
    return obj.get_display().menu(message, choices, default=default, cli_flag=cli_flag,
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 125, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 390, in _get_valid_int_ans
    ans = util.input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 68, in input_with_timeout
    raise EOFError
EOFError
2023-10-26 11:05:59,145:ERROR:certbot._internal.log:An unexpected error occurred:
2023-10-26 11:05:59,145:ERROR:certbot._internal.log:EOFError
